// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Option from "@rescript/runtime/lib/es6/Belt_Option.js";

function init() {
  return {
    searchQuery: "",
    selectedLanguage: undefined,
    plugins: [],
    pluginCount: 844
  };
}

let samplePlugins = [
  {
    name: "nodejs",
    language: "JavaScript",
    url: "https://github.com/asdf-vm/asdf-nodejs"
  },
  {
    name: "rust",
    language: "Rust",
    url: "https://github.com/code-lever/asdf-rust"
  },
  {
    name: "python",
    language: "Python",
    url: "https://github.com/danhper/asdf-python"
  },
  {
    name: "ruby",
    language: "Ruby",
    url: "https://github.com/asdf-vm/asdf-ruby"
  },
  {
    name: "erlang",
    language: "Erlang",
    url: "https://github.com/asdf-vm/asdf-erlang"
  }
];

function filterPlugins(plugins, query, lang) {
  return (plugins.filter(p => {
      const matchesQuery = query === "" || p.name.includes(query);
      const matchesLang = langStr === "" || p.language === langStr;
      return matchesQuery && matchesLang;
    }));
}

function update(model, msg) {
  if (typeof msg !== "object") {
    let filtered = filterPlugins(samplePlugins, model.searchQuery, undefined);
    return {
      searchQuery: model.searchQuery,
      selectedLanguage: undefined,
      plugins: filtered,
      pluginCount: model.pluginCount
    };
  }
  if (msg.TAG === "UpdateSearch") {
    let query = msg._0;
    let filtered$1 = filterPlugins(samplePlugins, query, model.selectedLanguage);
    return {
      searchQuery: query,
      selectedLanguage: model.selectedLanguage,
      plugins: filtered$1,
      pluginCount: model.pluginCount
    };
  }
  let lang = msg._0;
  let filtered$2 = filterPlugins(samplePlugins, model.searchQuery, lang);
  return {
    searchQuery: model.searchQuery,
    selectedLanguage: lang,
    plugins: filtered$2,
    pluginCount: model.pluginCount
  };
}

function render(model) {
  let pluginsLen = model.plugins.length;
  return "asdf-plugins - Search: " + model.searchQuery + " | Language: " + Belt_Option.getWithDefault(model.selectedLanguage, "All") + " | Found: " + String(pluginsLen);
}

export {
  init,
  samplePlugins,
  filterPlugins,
  update,
  render,
}
/* No side effect */
